### PR TITLE
Add netloc check to validate_url

### PR DESCRIPTION
**Pull request by dmuhs**
I have added another check to the url validation util so that urls like `http://` or `https://foo` are not considered valid anymore. My editor also removed some trailing whitespaces. :)

### CODE REVIEW

**Comment by ColdHeat** [comment]
Not sure I agree with this check. http:// isn't a valid url but http://foo is valid.

**Comment by dmuhs** [comment]
I don't know how realistic it is to include bare TLDs in url validation as most of them don't resolve anyways (_trivia_: http://to being one of the few). The dot check was meant to make sure we're at least on a domain level without having to use a regex.

**Comment by ColdHeat** [comment]
They're often used to access internal only infrastructure. I don't see much harm in having them for those that will use it. And if they don't resolve, then when used on the public internet, some people's websites just don't load.

**Comment by dmuhs** [comment]
You're right. Thanks for pointing that out! I guess it's not that big of a deal then.

**Comment by ColdHeat** [comment]
:smile:

**Pull request closed without merging**
