### PR TITLE
enable max-attempts per challenge setting

### PR DESCRIPTION
**Pull request by slinkymanbyday**
This allows admin to set a maximum number of attempts per challenge (0 to disable, which is default).

If max attempts is reached, challenge is marked red and displays appropriate error message when more solutions are submitted.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Hmm... 

CSAW, what CTFd was written for, does not restrict key submissions and no jeopardy based CTF I've ever seen does either. 

I have recently used CTFd in an graded class exercise which potentially could have benefited from a max attempts setting. But I'm not sure how beneficial it is to start converting CTFd into a homework grading site like WebAssign. 

I think a feature like this would be best kept in a plugin system which is what I hope to begin writing soon. 

What did you need a max attempts per challenge for?

**Comment by slinkymanbyday** [comment]
The CTF that I'm helping develop needs a max attempts per challenge. 

It's a closed CTF (invite only).

A CTF that i participated in (CySCA, also not public) also had max attempts per challenge.

It's fine if you don't want it in pulled here, just thought others might want it too.

**Comment by ColdHeat** [comment]
It's definitely useful which is why I'm sort of on the fence. Given the variety of CTF structures, a plugin system would be pretty good to have overall. To me something like this belongs more in a plugin.

**Comment by ColdHeat** [comment]
I'll move this into a plugin once a plugin system is setup but for now this is fine :)

**Pull request merged**
