### PR TITLE
Added Python3 compatibility

### LINKED ISSUE #214: Fix Python 3 compatability
Like a weenie, I dev on Python 2 so occasionally Python 3 breaking changes will be introduced. Need to root those out and fix those.

### PR DESCRIPTION
**Pull request by tjgerot**
Very few errors. Fixes #214

### CODE REVIEW

**Comment by ColdHeat** [comment]
Hmm I could've sworn there were more incompatibilities. I'll look into this and get back to you.

**Comment by ColdHeat** [comment]
```
~/Repositories/CTFd master
(ctfd) ❯ python3 serve.py
Traceback (most recent call last):
  File "serve.py", line 1, in <module>
    from CTFd import create_app
  File "/Users/kchung/Repositories/CTFd/CTFd/__init__.py", line 10, in <module>
    from utils import get_config, set_config, cache, migrate, migrate_upgrade
ModuleNotFoundError: No module named 'utils'
```

I think there are more issues than just some parens unfortunately.

**Comment by ColdHeat** [comment]
I fixed the rest of the issues. Should be much better. 

Thanks!

**Comment by tjgerot** [comment]
Sorry, should've been more clear. I didn't actually run it (helpful right?); just looked for the basics (print, except as, encodings, etc.) Your fixes look good!

**Comment by ColdHeat** [comment]
😄

**Pull request merged**
